tap "homebrew/services"
# Cross-platform make
brew "cmake"
# Open source programming language to build simple/reliable/efficient software
brew "go"
# Open-source, cross-platform JavaScript runtime environment
brew "node@22"
# Object-relational database system
brew "postgresql@14"
# Object-relational database system
brew "postgresql@15"
# Interpreted, interactive, object-oriented programming language
brew "python@3.10"
# Interpreted, interactive, object-oriented programming language
brew "python@3.9"
# Persistent key-value database, with built-in net interface
brew "redis"
# Open-source code editor
cask "visual-studio-code"
vscode "ahmadalli.vscode-nginx-conf"
vscode "ashley-chen-738.monokai-light-custom"
vscode "batisteo.vscode-django"
vscode "charliermarsh.ruff"
vscode "cweijan.dbclient-jdbc"
vscode "cweijan.vscode-database-client2"
vscode "dart-code.dart-code"
vscode "dart-code.flutter"
vscode "docker.docker"
vscode "github.github-vscode-theme"
vscode "golang.go"
vscode "humao.rest-client"
vscode "mechatroner.rainbow-csv"
vscode "monokai.theme-monokai-pro-vscode"
vscode "ms-azuretools.vscode-containers"
vscode "ms-azuretools.vscode-docker"
vscode "ms-ceintl.vscode-language-pack-ru"
vscode "ms-dotnettools.csdevkit"
vscode "ms-dotnettools.csharp"
vscode "ms-dotnettools.vscode-dotnet-runtime"
vscode "ms-python.debugpy"
vscode "ms-python.flake8"
vscode "ms-python.isort"
vscode "ms-python.python"
vscode "ms-python.vscode-pylance"
vscode "ms-python.vscode-python-envs"
vscode "njqdev.vscode-python-typehint"
vscode "pkief.material-icon-theme"
vscode "postman.postman-for-vscode"
vscode "qwtel.sqlite-viewer"
vscode "softwaredotcom.swdc-vscode"
vscode "tamasfe.even-better-toml"
vscode "visualstudioexptteam.intellicode-api-usage-examples"
vscode "visualstudioexptteam.vscodeintellicode"
vscode "visualstudioexptteam.vscodeintellicode-completions"
vscode "wholroyd.jinja"
vscode "zoxon.monokai-light"
go "github.com/go-delve/delve/cmd/dlv"
go "github.com/pressly/goose/v3/cmd/goose"
go "golang.org/x/tools/gopls"
go "honnef.co/go/tools/cmd/staticcheck"
